name: Secure Share Integration

on:
  issue_comment:
    types: [created]

# github.event.issue.number

env:
  CMD: /virtru
  CMD_REQ: request

jobs:
  issue_comment:
    name: Issue Comment
    if: ${{ startsWith(github.event.comment.body, '/virtru') }}
    runs-on: ubuntu-latest
    steps:
      - name: Virtru - Request data
        if: ${{ startsWith(github.event.comment.body, '/virtru request') }}
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const command = '${ github.env.CMD } ${ github.env.CMD_REQ }'
            const comment = context.body
            const cleanComment = comment.substring(0, command.length)

            const {number: issue_number, owner, repo} = context.issue
            const baseUrl = 'https://secure.develop.virtru.com/secure-share'
            const regexp = /^\/virtru request\s+([^@]+@[^\s]+)\s+(@[a-zA-Z0-9_-]+)/


            // Parse Message
            let email = ''
            let from = ''
            const match = regexp.exec(comment);
            if (match) {
              email = match[1];
              from = match[2];
            }

            // Fns
            function makeLink(email) {
              return `${ baseUrl }/${ email }?ch=github&oid=${ context.repository }#${ issue_number }`
            }

            function createComment(body) {
              github.rest.issues.createComment({ issue_number, owner, repo, body })
            }

            // Success and failure messages
            if (email && from) {
              createComment(`@${ from } you have been asked to securely share data with ${ context.author }. Please use this url ${ makeLink(email) }`)
            } else {
              createComment(`:no_entry: @${ context.author } please use the format \`/virtru request <your email> <requesting username>\``)
            }