name: Secure Share Integration

on:
  issue_comment:
    types: [created]

# github.event.issue.number

jobs:
  issue_comment:
    name: Issue Comment
    runs-on: ubuntu-latest
    steps:
      - name: Virtru - Request data
        uses: actions/github-script@v5
        if: startsWith(${{ github.event.comment.body }}, '/virtru request')
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const {number: issue_number, owner, repo} = context.issue
            const baseUrl = 'https://secure.develop.virtru.com/secure-share'
            const regexp = /^\/virtru request\s+([^@]+@[^\s]+)\s+(@[a-zA-Z0-9_-]+)/

            function link(email) {
              return `${ baseUrl }/${ email }?ch=github&oid=${ context.repository }#${ issue_number }`
            }

            function comment(body) {
              github.rest.issues.createComment({ issue_number, owner, repo, body })
            }

            // Parse Message

            let email = ''
            let from = ''
            const match = regexp.exec(context.body);
            if (match) {
              email = match[1];
              from = match[2];
            }

            // Success and failure messages
            if (email && from) {
              comment(`@${ from } you have been asked to securely share data with ${ context.author }. Please use this url ${ link(email) }`)
            } else {
              comment(`:no_entry: @${ from } please use the format \`/virtru request <your email> <requesting username>\``)
            }